### ISSUE TITLE
Issue FLutterAarPLugin

### ISSUE THREAD

**Issue by surajsahani** [siyehua/flutter_aar#3]
e: /home/martial/.pub-cache/hosted/pub.dev/flutter_aar-0.0.5/android/src/main/kotlin/com/siyehua/flutter_aar/FlutterAarPlugin.kt: (4, 20): Unresolved reference: mylibrary2
e: /home/martial/.pub-cache/hosted/pub.dev/flutter_aar-0.0.5/android/src/main/kotlin/com/siyehua/flutter_aar/FlutterAarPlugin.kt: (28, 20): Unresolved reference: MyAarClass

**Comment by siyehua** [comment]
The MyAarClass or package is in com.siyehua.flataar-mylibrary2-1.0.2.aar file. it's in android/libs dir. Do you remove this file? it's a test local aar file.

**Comment by surajsahani** [comment]
![Screenshot from 2023-03-01 15-42-41](https://user-images.githubusercontent.com/22853459/222109610-49ec1282-3a1b-4031-91d8-c2e6dcbe6225.png)
By default flutter does not create lib folder inside android? Do i need to create one?

**Comment by siyehua** [comment]
Yes, you should create the libs dir. You can refer to this project.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/9376247/222110934-c78cf6fb-be22-4c43-8d9f-267336674aa0.png">

**Comment by surajsahani** [comment]
Getting same issues again, i tried with new project as well, but lib folder does not generate can you provide me some sample projects in which this library has implemented?

**Comment by siyehua** [comment]
This project is an example. You can build and run it.  
The libs folder can't generate by IDE auto, you should create it yourself.

First: create a project
Second: create the libs folder
and then copy the code from the [readme.md](https://github.com/siyehua/flutter_aar) file.

**Comment by siyehua** [comment]
> Getting same issues again, i tried with new project as well, but lib folder does not generate can you provide me some sample projects in which this library has implemented?

Because this solution is only a gradle script, so I don't build it to a library.

**Comment by surajsahani** [comment]
![Screenshot from 2023-03-01 16-47-22](https://user-images.githubusercontent.com/22853459/222124654-9001c991-5df0-4cce-bc48-998396dd3747.png)
Able to go one step further. But now getting this issue? any idea!!

**Comment by siyehua** [comment]
> ![Screenshot from 2023-03-01 16-47-22](https://user-images.githubusercontent.com/22853459/222124654-9001c991-5df0-4cce-bc48-998396dd3747.png) Able to go one step further. But now getting this issue? any idea!!

show me your code: build.gradle

**Comment by surajsahani** [comment]
**android/build.gradle**

import java.security.MessageDigest
import java.security.NoSuchAlgorithmException

buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

String localMavenPath = project.mkdir("build").absolutePath

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "file://$localMavenPath" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
String aarPath = localMavenPath
task useAar {
    File file = project.file("libs")
    if (file.exists() && file.isDirectory()) {
        file.listFiles(new FileFilter() {
            @Override
            boolean accept(File pathname) {
                return pathname.name.endsWith(".aar")
            }
        }).each { item ->
            String aarName = item.name.substring(0, item.name.length() - 4)
            String[] aarInfo = aarName.split("-")
            String sha1 = getFileSha1(item)
            String md5 = getFileMD5(item)
            println("aar: " + aarInfo + " file sha1:" + sha1 + " md5:" + md5)
            String fromStr = item.path
            String intoStr = aarPath + "/" + aarInfo[0].replace(".", "/") + "/" + aarInfo[1] + "/" + aarInfo[2]
            String newName = aarInfo[1] + "-" + aarInfo[2] + ".aar"

            project.copy {
                from fromStr
                into intoStr
                rename(item.name, newName)
            }

            project.file(intoStr + "/" + newName + ".md5").write(md5)
            project.file(intoStr + "/" + newName + ".sha1").write(sha1)

            String pomPath = intoStr + "/" + newName.substring(0, newName.length() - 4) + ".pom"
            project.file(pomPath).write(createPomStr(aarInfo[0], aarInfo[1], aarInfo[2]))
            project.file(pomPath + ".md5").write(getFileMD5(project.file(pomPath)))
            project.file(pomPath + ".sha1").write(getFileSha1(project.file(pomPath)))

            String metadataPath = project.file(intoStr).getParentFile().path + "/maven-metadata.xml"
            project.file(metadataPath).write(createMetadataStr(aarInfo[0], aarInfo[1], aarInfo[2]))
            project.file(metadataPath + ".md5").write(getFileMD5(project.file(metadataPath)))
            project.file(metadataPath + ".sha1").write(getFileSha1(project.file(metadataPath)))
            dependencies {
                implementation "${aarInfo[0]}:${aarInfo[1]}:${aarInfo[2]}"
            }
        }
    }
}

public static String createMetadataStr(String groupId, String artifactId, String version) {
    return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<metadata>\n" +
            "  <groupId>$groupId</groupId>\n" +
            "  <artifactId>$artifactId</artifactId>\n" +
            "  <versioning>\n" +
            "    <release>$version</release>\n" +
            "    <versions>\n" +
            "      <version>$version</version>\n" +
            "    </versions>\n" +
            "    <lastUpdated>${new Date().format('yyyyMMdd')}000000</lastUpdated>\n" +
            "  </versioning>\n" +
            "</metadata>\n"
}

public static String createPomStr(String groupId, String artifactId, String version) {
    return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<project xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd\" xmlns=\"http://maven.apache.org/POM/4.0.0\"\n" +
            "    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
            "  <modelVersion>4.0.0</modelVersion>\n" +
            "  <groupId>$groupId</groupId>\n" +
            "  <artifactId>$artifactId</artifactId>\n" +
            "  <version>$version</version>\n" +
            "  <packaging>aar</packaging>\n" +
            "</project>\n"
}

public static String getFileSha1(File file) {
    FileInputStream input = null;
    try {
        input = new FileInputStream(file);
        MessageDigest digest = MessageDigest.getInstance("SHA-1");
        byte[] buffer = new byte[1024 * 1024 * 10];

        int len = 0;
        while ((len = input.read(buffer)) > 0) {
            digest.update(buffer, 0, len);
        }
        String sha1 = new BigInteger(1, digest.digest()).toString(16);
        int length = 40 - sha1.length();
        if (length > 0) {
            for (int i = 0; i < length; i++) {
                sha1 = "0" + sha1;
            }
        }
        return sha1;
    }
    catch (IOException e) {
        System.out.println(e);
    }
    catch (NoSuchAlgorithmException e) {
        System.out.println(e);
    }
    finally {
        try {
            if (input != null) {
                input.close();
            }
        }
        catch (IOException e) {
            System.out.println(e);
        }
    }
}

public static String getFileMD5(File file) {
    FileInputStream input = null;
    try {
        input = new FileInputStream(file);
        MessageDigest digest = MessageDigest.getInstance("MD5");
        byte[] buffer = new byte[1024 * 1024 * 10];

        int len = 0;
        while ((len = input.read(buffer)) > 0) {
            digest.update(buffer, 0, len);
        }
        String md5 = new BigInteger(1, digest.digest()).toString(16);
        int length = 32 - md5.length();
        if (length > 0) {
            for (int i = 0; i < length; i++) {
                md5 = "0" + md5;
            }
        }
        return md5;
    }
    catch (IOException e) {
        System.out.println(e);
    }
    catch (NoSuchAlgorithmException e) {
        System.out.println(e);
    }
    finally {
        try {
            if (input != null) {
                input.close();
            }
        }
        catch (IOException e) {
            System.out.println(e);
        }
    }
}

**Comment by siyehua** [comment]
Because this project was created two years ago. The flutter android project has changed gradle and app dir tree.

You should create libs folder in the android/app/ path, and add my code in the android/app/build.gradle.

This is my example, and it works.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/9376247/222132931-032c7dd9-8a16-4d7b-9b36-24176b284aa3.png">

**Comment by surajsahani** [comment]
Okay, if possible can you check where i'm going wrong, i have uploaded entire project here.
https://github.com/surajsahani/flutter-aar-demo

**Comment by surajsahani** [comment]
I think i have found the issue.
1) We need to create libs folder in android project. not inside app. after this only library able to recoganized aar files

**Comment by surajsahani** [comment]
A problem occurred evaluating root project 'android'.
> Could not find method implementation() for arguments [com.logger:sdk:1.0.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

showing error on this line

```
            dependencies {
                implementation "${aarInfo[0]}:${aarInfo[1]}:${aarInfo[2]}"
            }
```

**Comment by siyehua** [comment]
> Okay, if possible can you check where i'm going wrong, i have uploaded entire project here. https://github.com/surajsahani/flutter-aar-demo

fix:

https://github.com/surajsahani/flutter-aar-demo/pull/1

**Comment by surajsahani** [comment]
same issue still there, i have taken the latest pull

![Screenshot from 2023-03-02 09-28-07](https://user-images.githubusercontent.com/22853459/222327857-8af2b218-c6fc-4c63-94e5-479899568ed1.png)

**Comment by siyehua** [comment]
> same issue still there, i have taken the latest pull
> 
> ![Screenshot from 2023-03-02 09-28-07](https://user-images.githubusercontent.com/22853459/222327857-8af2b218-c6fc-4c63-94e5-479899568ed1.png)

print log: aar com.logger sdk 1.0.1, this aar is yours, so you should use your code, no mine.
<img width="2017" alt="image" src="https://user-images.githubusercontent.com/9376247/222345993-bceeea79-f880-462f-bb1a-ec1ddac2e3da.png">
